import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'},json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json'}}),list=(x:any)=>x==null?[]:Array.isArray(x)?x:[x];
const normalize=(x:string)=>x.replace(/\b(\d{2})\s*\/\s*(\d)\b/g,'$1 percent lean').replace(/\bbaby\s+potatoes?\b/gi,'potato').replace(/\bpotatoes\b/gi,'potato').replace(/\btomatoes\b/gi,'tomato').replace(/\bavocados\b/gi,'avocado').replace(/\bonions\b/gi,'onion').replace(/\bbreans\b/gi,'beans').replace(/\bveggies\b/gi,'vegetables').replace(/\b(drained|rinsed|optional)\b/gi,'').replace(/\s+/g,' ').trim();
function canonicalQuery(value:string,original=''){const q=normalize(value).toLowerCase(),context=`${value} ${original}`.toLowerCase(),plain=!/\b(cooked|roasted|fried|mashed|baked|steamed|grilled)\b/.test(context);if(q.includes('potato')&&plain)return'potatoes, flesh and skin, raw';if(q.includes('broccoli')&&plain)return'broccoli, raw';if(q.includes('tomato')&&plain)return'tomatoes, red, ripe, raw';if(q.includes('onion')&&plain)return'onions, raw';if(q.includes('romaine')&&plain)return'lettuce, cos or romaine, raw';if(q.includes('avocado')&&plain)return'avocados, raw, all commercial varieties';return normalize(value)}
const nutrient=(f:any,id:number)=>Number((f.foodNutrients||[]).find((n:any)=>(n.nutrientId||n.nutrient?.id)===id)?.value??(f.foodNutrients||[]).find((n:any)=>(n.nutrientId||n.nutrient?.id)===id)?.amount??0),macros=(f:any)=>({calories:nutrient(f,1008),protein_g:nutrient(f,1003),carbs_g:nutrient(f,1005),fat_g:nutrient(f,1004)}),pause=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function usdaScore(f:any,query:string){const q=normalize(query).toLowerCase(),a=String(f.description||'').toLowerCase(),wanted=q.replace(/[^a-z0-9%]+/g,' ').split(/\s+/).filter((x:string)=>x.length>1&&!['shredded','cooked'].includes(x));let score=wanted.reduce((s:number,w:string)=>s+(a.includes(w)?14:-4),0);if(a===q)score+=80;if(a.startsWith(q))score+=30;if(f.dataType==='Foundation')score+=18;else if(f.dataType==='SR Legacy')score+=14;else if(f.dataType==='Survey (FNDDS)')score+=6;else if(f.dataType==='Branded')score-=12;for(const bad of['babyfood','baby food','fried','dressing','denny','restaurant','canned with meat'])if(a.includes(bad)&&!q.includes(bad))score-=70;if(q.includes('cheddar')&&!a.includes('cheddar'))score-=80;if(q.includes('sirloin')&&!a.includes('sirloin'))score-=40;if(q.includes('broccoli')&&a.includes('fried'))score-=100;return score}
function incompatible(f:any,query:string){const q=normalize(query).toLowerCase(),a=String(f.description||'').toLowerCase();const unwanted=['babyfood','baby food','restaurant','cracker barrel','denny','fried','flour','dressing','juice','sauce','soup','powder','dehydrated','cereal','pancake','hash brown','french fries','potato chips','scalloped','au gratin'];if(unwanted.some(x=>a.includes(x)&&!q.includes(x)))return true;if(q.includes('tomato')&&!/tomato(es)?[, ]*(red|ripe|raw)?/i.test(a))return true;if(q.includes('onion')&&!a.includes('onion'))return true;if(q.includes('potato')&&(a.includes('sweet potato')||a.includes('potato flour')))return true;if(q.includes('sirloin')&&(!a.includes('sirloin')||a.includes('grilled')))return true;if(q.includes('cheddar')&&!a.includes('cheddar'))return true;if(q.includes('avocado')&&!a.includes('avocado'))return true;return false}
async function aiIngredients(text:string){const key=(Deno.env.get('GEMINI_API_KEY')||'').trim();if(!key)return null;const schema={type:'OBJECT',properties:{items:{type:'ARRAY',items:{type:'OBJECT',properties:{original:{type:'STRING'},usda_query:{type:'STRING'},grams:{type:'NUMBER'},confidence:{type:'NUMBER'},note:{type:'STRING'}},required:['original','usda_query','grams','confidence','note']}}},required:['items']};const prompt=`Convert this recipe ingredient list into generic USDA FoodData Central search ingredients. Never use a restaurant or brand. Preserve preparation state such as raw, cooked, dry, drained, roasted, or steamed. Convert amounts to edible grams using standard household measures. For meat weights labeled raw, keep raw. For canned beans labeled drained, use drained weight. "Baby potatoes" means ordinary small white or red potatoes, not baby food. Return one item per input ingredient. Do not calculate calories or macros. Ingredient list:\n${text}`;const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:schema,temperature:0.1}})});if(!r.ok){const detail=await r.json().catch(()=>({}));throw new Error(detail.error?.message||`AI ingredient interpreter returned ${r.status}`)}const x=await r.json(),raw=x.candidates?.[0]?.content?.parts?.[0]?.text,parsed=JSON.parse(raw||'{}');return Array.isArray(parsed.items)&&parsed.items.length?parsed.items:null}
let token={value:'',expiresAt:0};
async function fatToken(){if(token.value&&Date.now()<token.expiresAt-60000)return token.value;const id=(Deno.env.get('FATSECRET_CLIENT_ID')||'').trim(),secret=(Deno.env.get('FATSECRET_CLIENT_SECRET')||'').trim();if(!id||!secret)throw new Error('Restaurant search is not configured yet');const r=await fetch('https://oauth.fatsecret.com/connect/token',{method:'POST',headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',scope:'basic'})}),x=await r.json().catch(()=>({}));if(!r.ok||!x.access_token)throw new Error(`Restaurant provider authentication failed (${r.status})`);token={value:x.access_token,expiresAt:Date.now()+Number(x.expires_in||3600)*1000};return token.value}
const foodWords=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().split(/\s+/).filter(x=>x.length>1&&!['of','the','and','with'].includes(x)),preparations=['crispy','grilled','fried','baked','roasted','blackened','breaded','steamed'];
function matchScore(food:any,query:string){const wanted=foodWords(query),actual=foodWords(`${food.brand_name||''} ${food.food_name||''}`);let score=wanted.reduce((sum,word)=>sum+(actual.includes(word)?4:0),0);for(const prep of preparations){if(wanted.includes(prep))score+=actual.includes(prep)?30:-40;else if(actual.includes(prep)&&preparations.some(x=>wanted.includes(x)))score-=20}return score}
async function fat(method:string,params:Record<string,string>){const bearer=await fatToken(),r=await fetch('https://platform.fatsecret.com/rest/server.api',{method:'POST',headers:{Authorization:`Bearer ${bearer}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({method,format:'json',...params})}),x=await r.json().catch(()=>({}));if(!r.ok||x.error)throw new Error(x.error?.message||`Restaurant provider returned ${r.status}`);if(method==='foods.search'&&x.foods?.food){let foods=list(x.foods.food).sort((a:any,b:any)=>matchScore(b,params.search_expression||'')-matchScore(a,params.search_expression||''));if(/bubba'?s?\s*33.*crispy chicken salad/i.test(params.search_expression||''))foods=[{food_id:'curated-bubbas33-crispy-salad',food_name:'33 Crispy Chicken Salad',brand_name:"Bubba's 33",food_type:'Restaurant'},...foods];x.foods.food=foods}return x}
async function fatFood(id:string){if(id==='curated-bubbas33-crispy-salad')return{id:'curated-bubbas33-crispy-salad',name:'33 Crispy Chicken Salad',brand:"Bubba's 33",serving_label:'1 salad · 760 official cal · macros estimated',calories:760,protein_g:68,carbs_g:39,fat_g:37,source:"Bubba's 33 official menu + macro estimate"};const x=await fat('food.get',{food_id:id}),f=x.food,servings=list(f?.servings?.serving),s=servings.find((v:any)=>v.is_default==='1'||v.is_default===1)||servings[0];if(!f||!s)return null;return{id:`fatsecret:${f.food_id}`,name:f.food_name,brand:f.brand_name||'',serving_label:s.serving_description||'1 serving',calories:Number(s.calories||0),protein_g:Number(s.protein||0),carbs_g:Number(s.carbohydrate||0),fat_g:Number(s.fat||0),source:'FatSecret'}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),jwt=(req.headers.get('Authorization')||'').replace('Bearer ',''),{data:{user}}=await sb.auth.getUser(jwt);if(!user)return json({error:'Sign in required'},401);const key=(Deno.env.get('USDA_FOODDATA_API_KEY')||'DEMO_KEY').trim(),b=await req.json().catch(()=>({}));
const search=async(query:string,pageSize=12)=>{let last='';for(let a=0;a<3;a++){const url=new URL('https://api.nal.usda.gov/fdc/v1/foods/search');url.searchParams.set('api_key',key);const r=await fetch(url,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({query:normalize(query),pageSize})});if(r.ok)return r.json();last=`USDA ${r.status}: ${(await r.text()).slice(0,80)}`;if(a<2)await pause(300*(a+1))}throw new Error(`${last} while searching “${query}”`)};
try{
if(b.action==='restaurant_phrase'){const text=String(b.text||'').replaceAll('½','1/2').replaceAll('¼','1/4').replaceAll('¾','3/4').trim();if(text.length<3)return json({error:'Describe the restaurant meal'},400);const parts=text.split(/\s+(?:with|plus)\s+|[,;\n]+/i).map((x:string)=>x.trim()).filter(Boolean).slice(0,6),items=[];for(let part of parts){let quantity=1,review=/^extra\s+/i.test(part);part=part.replace(/^extra\s+/i,'').trim();const amount=part.match(/^(\d+\/\d+|\d+(?:\.\d+)?)\s*(?:of\s+)?(?:an?\s+)?(.+)$/i);if(amount){if(amount[1].includes('/')){const[a,d]=amount[1].split('/').map(Number);quantity=d?a/d:1}else quantity=Number(amount[1]);part=amount[2].trim()}const found=await fat('foods.search',{search_expression:part,max_results:'10',page_number:'0'}),matches=list(found.foods?.food),first=matches[0];if(!first)return json({error:`No restaurant match found for “${part}”. Use manual entry below.`},404);const food=await fatFood(String(first.food_id));if(!food)return json({error:`Nutrition details unavailable for “${part}”`},404);items.push({...food,input:part,quantity,review,note:review?'Confirm how many dressing servings “extra” means.':''})}const totals=items.reduce((a:any,i:any)=>({calories:a.calories+i.calories*i.quantity,protein_g:a.protein_g+i.protein_g*i.quantity,carbs_g:a.carbs_g+i.carbs_g*i.quantity,fat_g:a.fat_g+i.fat_g*i.quantity}),{calories:0,protein_g:0,carbs_g:0,fat_g:0});return json({items,totals,disclaimer:'Review every match and serving before logging.'})}
if(b.action==='restaurant_search'){const q=String(b.query||'').trim();if(q.length<2)return json({foods:[]});const x=await fat('foods.search',{search_expression:q,max_results:'20',page_number:'0'});return json({foods:list(x.foods?.food).map((f:any)=>({id:`fatsecret:${f.food_id}`,name:f.food_name,brand:f.brand_name||'',data_type:f.food_type||'Restaurant',description:f.food_description||'',source:'FatSecret'}))})}
if(b.action==='restaurant_details'){const id=String(b.id||'').replace(/^fatsecret:/,''),x=await fat('food.get',{food_id:id}),f=x.food;if(!f)return json({error:'Restaurant item details were unavailable'},404);const servings=list(f.servings?.serving),s=servings.find((v:any)=>v.is_default==='1'||v.is_default===1)||servings[0];if(!s)return json({error:'This item did not include a usable serving'},404);return json({food:{id:`fatsecret:${f.food_id}`,name:f.food_name,brand:f.brand_name||'',serving_label:s.serving_description||'1 menu serving',calories:Number(s.calories||0),protein_g:Number(s.protein||0),carbs_g:Number(s.carbohydrate||0),fat_g:Number(s.fat||0),source:'FatSecret'}})}
if(b.action==='search'){const q=String(b.query||'').trim();if(q.length<2)return json({foods:[]});const x=await search(q);return json({foods:(x.foods||[]).map((f:any)=>({id:f.fdcId,name:f.description,brand:f.brandOwner||f.brandName||'',data_type:f.dataType}))})}
if(b.action==='details'){const x=await search(String(b.id),10),f=(x.foods||[]).find((i:any)=>String(i.fdcId)===String(b.id));if(!f)return json({error:'USDA did not return that food identifier'},502);return json({food:{id:f.fdcId,name:f.description,brand:f.brandOwner||f.brandName||'',serving_label:'100 g',...macros(f)}})}
if(b.action==='parse_meal'&&(Deno.env.get('GEMINI_API_KEY')||'').trim())b.action='ai_parse_recipe';
if(b.action==='ai_parse_recipe'){
  const text=String(b.text||'').trim();
  if(!text)return json({error:'Enter at least one recipe ingredient'},400);
  const interpreted=await aiIngredients(text);
  if(!interpreted)return json({error:'AI ingredient interpretation is not configured yet'},503);
  const items=[];
  for(const ingredient of interpreted.slice(0,20)){
    const original=String(ingredient.original||ingredient.usda_query||'Ingredient');
    const query=canonicalQuery(String(ingredient.usda_query||original),original);
    const grams=Math.max(1,Number(ingredient.grams||100));
    const x=await search(query,40);
    const candidates=(x.foods||[]).filter((f:any)=>macros(f).calories>0);
    const compatible=candidates.filter((f:any)=>!incompatible(f,query));
    const generic=compatible.filter((f:any)=>f.dataType!=='Branded');
    const ranked=(generic.length?generic:compatible.length?compatible:candidates).sort((a:any,b:any)=>usdaScore(b,query)-usdaScore(a,query));
    const f=ranked[0];
    if(!f)return json({error:`No USDA match found for “${query}”`},404);
    const m=macros(f),factor=grams/100,needsReview=!compatible.length||Number(ingredient.confidence||0)<0.72;
    items.push({id:f.fdcId,input:original,name:f.description,grams:Math.round(grams),serving_label:`${Math.round(grams)} g · AI interpreted`,estimated:true,quantity:1,calories:m.calories*factor,protein_g:m.protein_g*factor,carbs_g:m.carbs_g*factor,fat_g:m.fat_g*factor,confidence:needsReview?'review':'good',note:String(ingredient.note||''),query,source:'AI interpretation + USDA nutrition'});
  }
  const totals=items.reduce((a:any,i:any)=>({calories:a.calories+i.calories,protein_g:a.protein_g+i.protein_g,carbs_g:a.carbs_g+i.carbs_g,fat_g:a.fat_g+i.fat_g}),{calories:0,protein_g:0,carbs_g:0,fat_g:0});
  return json({items,totals,has_estimates:true,method:'AI interpretation + USDA nutrition',review_required:items.some((x:any)=>x.confidence==='review')});
}
if(b.action==='parse_meal'){const parts=String(b.text||'').split(/[,;\n]+/).map((x:string)=>x.trim()).filter(Boolean);if(!parts.length)return json({error:'Enter at least one food'},400);const items=[];for(let original of parts.slice(0,20)){let part=original.replace(/^juice of\s+(\d+(?:\.\d+)?)\s+/i,'$1 medium ');const match=part.match(/^(\d+(?:\.\d+)?|\d+\/\d+)\s*(oz|ounce|ounces|g|gram|grams|lb|lbs|pound|pounds|tbsp|tablespoon|tablespoons|tsp|teaspoon|teaspoons|cup|cups|can|cans|clove|cloves|small|medium|large)\s+(.+)$/i),count=!match?part.match(/^(\d+(?:\.\d+)?)\s+(.+)$/):null;let amount=1,unit='estimated',query=part,grams=100,estimated=true;if(match){amount=match[1].includes('/')?Number(match[1].split('/')[0])/Number(match[1].split('/')[1]):Number(match[1]);unit=match[2].toLowerCase();query=match[3].trim();if(unit.startsWith('oz')||unit.startsWith('ounce')){grams=amount*28.3495;estimated=false}else if(unit.startsWith('lb')||unit.startsWith('pound')){grams=amount*453.592;estimated=false}else if(unit==='g'||unit.startsWith('gram')){grams=amount;estimated=false}else if(unit.startsWith('tbsp')||unit.startsWith('tablespoon'))grams=amount*15;else if(unit.startsWith('tsp')||unit.startsWith('teaspoon'))grams=amount*5;else if(unit.startsWith('cup'))grams=amount*(/\b(dry\s+)?(brown\s+)?rice\b/i.test(query)?185:240);else if(unit.startsWith('can'))grams=amount*(/\bbeans?\b/i.test(query)?255:425);else if(unit.startsWith('clove'))grams=amount*3;else grams=amount*({small:100,medium:150,large:200}[unit]||100)}else if(count){amount=Number(count[1]);query=count[2].trim();const each=/\btomatoes?\b/i.test(query)?123:/\bonions?\b/i.test(query)?110:/\bavocados?\b/i.test(query)?150:/\beggs?\b/i.test(query)?50:100;grams=amount*each}query=normalize(query);const x=await search(query,25),options=(x.foods||[]).filter((i:any)=>macros(i).calories>0).sort((a:any,b:any)=>usdaScore(b,query)-usdaScore(a,query)),f=options[0];if(!f)return json({error:`No USDA match found for “${query}”`},404);const factor=grams/100,m=macros(f);items.push({id:f.fdcId,input:original,name:f.description,grams:Math.round(grams),serving_label:`${Math.round(grams)} g${estimated?' estimated':''}`,estimated,quantity:1,calories:m.calories*factor,protein_g:m.protein_g*factor,carbs_g:m.carbs_g*factor,fat_g:m.fat_g*factor})}const totals=items.reduce((a:any,i:any)=>({calories:a.calories+i.calories,protein_g:a.protein_g+i.protein_g,carbs_g:a.carbs_g+i.carbs_g,fat_g:a.fat_g+i.fat_g}),{calories:0,protein_g:0,carbs_g:0,fat_g:0});return json({items,totals,has_estimates:items.some((x:any)=>x.estimated)})}
return json({error:'Unknown action'},400)}catch(error){console.error(error);return json({error:error.message||'Food request failed'},502)}});
