import React, { useEffect, useState } from 'react'

export default function DayRhythm({ supabase, localDateKey }) {
  const [data,setData]=useState(null),[reflection,setReflection]=useState(''),[status,setStatus]=useState('complete'),[carry,setCarry]=useState(true),[msg,setMsg]=useState('')
  const evening=new Date().getHours()>=17
  async function load(){const{data:{user}}=await supabase.auth.getUser();const{data:h}=await supabase.from('ft_households').select('id').limit(1).single();const{data:s}=await supabase.from('ft_member_settings').select('*').eq('household_id',h.id).eq('user_id',user.id).single();const start=s.personal_start_date?new Date(`${s.personal_start_date}T00:00:00`):new Date(),day=Math.max(1,Math.min(75,Math.floor((new Date().setHours(0,0,0,0)-start.setHours(0,0,0,0))/86400000)+1)),cycle=s.program_cycle||1,today=localDateKey();const[{data:check},{data:tasks},{data:food},{data:water},{data:{session}}]=await Promise.all([supabase.from('ft_daily_checkins').select('*').eq('household_id',h.id).eq('user_id',user.id).eq('program_cycle',cycle).eq('program_day',day).maybeSingle(),supabase.from('ft_tasks').select('*').eq('assigned_to',user.id).eq('status','open').or(`due_date.is.null,due_date.lte.${today}`).order('priority',{ascending:false}).order('due_time'),supabase.from('ft_food_logs').select('calories,protein_g').eq('user_id',user.id).eq('logged_on',today),supabase.from('ft_water_logs').select('ounces').eq('user_id',user.id).eq('logged_on',today),supabase.auth.getSession()]);let events=[];try{const x=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ft-google-calendar`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'events'})}).then(r=>r.json());events=(x.events||[]).filter(e=>(e.start.includes('T')?localDateKey(e.start):e.start)===today).slice(0,4)}catch{}setData({user,h,s,day,cycle,today,check,tasks:tasks||[],food:food||[],water:water||[],events});setReflection(check?.journal_text||'');setStatus(check?.status==='in_progress'?'complete':check?.status||'complete')}
  useEffect(()=>{load()},[])
  if(!data)return null
  const done=data.check?.completed_actions?.length||0,calories=data.food.reduce((a,x)=>a+Number(x.calories||0),0),protein=data.food.reduce((a,x)=>a+Number(x.protein_g||0),0),water=data.water.reduce((a,x)=>a+Number(x.ounces||0),0)
  async function closeDay(){setMsg('Closing the day…');const row={household_id:data.h.id,user_id:data.user.id,program_cycle:data.cycle,program_day:data.day,capacity:data.check?.capacity||'green',completed_actions:data.check?.completed_actions||[],journal_text:reflection,status,updated_at:new Date().toISOString()};const{error}=await supabase.from('ft_daily_checkins').upsert(row,{onConflict:'household_id,user_id,program_cycle,program_day'});if(!error&&carry&&data.tasks.length){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);await supabase.from('ft_tasks').update({due_date:localDateKey(tomorrow),updated_at:new Date().toISOString()}).in('id',data.tasks.map(t=>t.id))}setMsg(error?error.message:'Day closed. Tomorrow can begin clean.');if(!error)setTimeout(()=>window.location.reload(),700)}
  if(!evening)return <div className="page dayrhythm"><section className="morningplan"><div><p className="kicker">MORNING PLAN</p><h2>Protect the three things that matter most.</h2></div><div className="morningcolumns"><section><strong>Next on the calendar</strong>{data.events.slice(0,2).map(e=><p key={`${e.calendar}-${e.id}`}>{e.start.includes('T')&&<time>{new Date(e.start).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time>} {e.title}</p>)}{!data.events.length&&<p>Open schedule—use the space intentionally.</p>}</section><section><strong>Top priorities</strong>{data.tasks.slice(0,3).map(t=><p key={t.id}>{t.title}</p>)}{!data.tasks.length&&<p>Faith, movement, and one meaningful responsibility.</p>}</section></div></section></div>
  return <div className="page dayrhythm"><section className="eveningclose"><p className="kicker">EVENING SHUTDOWN</p><h2>Close the day with honesty and peace.</h2><div className="closemetrics"><div><strong>{done}/5</strong><span>faithful steps</span></div><div><strong>{Math.round(calories)}</strong><span>calories · {Math.round(protein)}g protein</span></div><div><strong>{water}</strong><span>oz water</span></div><div><strong>{data.tasks.length}</strong><span>open tasks</span></div></div><label>Where were you faithful today?<textarea value={reflection} onChange={e=>setReflection(e.target.value)}/></label><div className="closeoptions"><label>Day result<select value={status} onChange={e=>setStatus(e.target.value)}><option value="complete">Complete</option><option value="modified">Modified day</option><option value="incomplete">Incomplete</option></select></label>{data.tasks.length>0&&<label className="carry"><input type="checkbox" checked={carry} onChange={e=>setCarry(e.target.checked)}/> Move today’s unfinished tasks to tomorrow</label>}</div><button className="primary" onClick={closeDay}>Close my day</button>{msg&&<p className="message status">{msg}</p>}</section></div>
}
