import React, { useEffect, useState } from 'react'

export default function FamilyCoordination({household,supabase,localDateKey}){
 const[state,setState]=useState({tasks:[],members:[],userId:''}),[title,setTitle]=useState(''),[assigned,setAssigned]=useState(''),[when,setWhen]=useState('today'),[category,setCategory]=useState('family'),[recurrence,setRecurrence]=useState('none'),[msg,setMsg]=useState('')
 async function load(){const{data:{user}}=await supabase.auth.getUser();const[{data:tasks},{data:members}]=await Promise.all([supabase.from('ft_tasks').select('*').eq('household_id',household.id).eq('visibility','household').eq('status','open').order('due_date',{ascending:true,nullsFirst:true}).order('due_time'),supabase.from('ft_household_members').select('user_id').eq('household_id',household.id)]);const ids=(members||[]).map(m=>m.user_id),{data:profiles}=ids.length?await supabase.from('ft_profiles').select('id,display_name').in('id',ids):{data:[]};const profileNames=new Map((profiles||[]).map(profile=>[profile.id,profile.display_name]));const people=(members||[]).map(m=>({user_id:m.user_id,display_name:profileNames.get(m.user_id)||'Family member'}));setState({tasks:(tasks||[]).filter(t=>!t.due_date||t.due_date<=localDateKey()),members:people,userId:user.id});setAssigned(value=>value||user.id)}
 useEffect(()=>{load()},[household.id])
 const name=id=>state.members.find(m=>m.user_id===id)?.display_name||'Family member'
 async function add(e){e.preventDefault();const due=new Date();if(when==='tomorrow')due.setDate(due.getDate()+1);const{error}=await supabase.from('ft_tasks').insert({household_id:household.id,created_by:state.userId,assigned_to:assigned,title:title.trim(),category,recurrence,visibility:'household',due_date:localDateKey(due)});setMsg(error?error.message:recurrence==='none'?'Shared task added.':'Family rhythm added. It will repeat when completed.');if(!error){setTitle('');load()}}
 async function complete(task){const{error}=await supabase.rpc('ft_complete_task',{task_id:task.id});setMsg(error?error.message:'Shared task completed.');if(!error)load()}
 return <div className="page familycoordination"><section className="panel"><p className="kicker">FAMILY RHYTHM</p><h2>Know who is carrying what.</h2><p>Assign chores, meals, family check-ins, and shared responsibilities. Personal tasks and all health details remain private.</p><form onSubmit={add}><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Add a household responsibility…"/><select aria-label="Assign to" value={assigned} onChange={e=>setAssigned(e.target.value)}>{state.members.map(member=><option value={member.user_id} key={member.user_id}>{member.display_name}</option>)}</select><select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option value="family">Family</option><option value="home">Chore</option><option value="meal">Meal</option><option value="faith">Faith</option></select><select aria-label="Due" value={when} onChange={e=>setWhen(e.target.value)}><option value="today">Today</option><option value="tomorrow">Tomorrow</option></select><select aria-label="Repeat" value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="none">Once</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select><button className="primary">Assign</button></form><div className="rhythmtemplates"><span>Quick rhythms:</span><button onClick={()=>{setTitle('Family check-in');setCategory('family');setRecurrence('weekly')}}>Weekly family check-in</button><button onClick={()=>{setTitle('Plan family meals');setCategory('meal');setRecurrence('weekly')}}>Meal planning</button><button onClick={()=>{setTitle('Evening home reset');setCategory('home');setRecurrence('daily')}}>Home reset</button></div><div className="familytasklist">{state.tasks.map(task=><article key={task.id}><button disabled={task.assigned_to!==state.userId&&task.created_by!==state.userId} onClick={()=>complete(task)} aria-label={`Complete ${task.title}`}>✓</button><div><strong>{task.title}</strong><small>{name(task.assigned_to)} · {task.category||'family'}{task.recurrence&&task.recurrence!=='none'?` · repeats ${task.recurrence}`:''}{task.due_time?` · ${new Date(`2000-01-01T${task.due_time}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:''}</small></div>{task.assigned_to===state.userId&&<span>Yours</span>}</article>)}{!state.tasks.length&&<p className="muted">No shared responsibilities are waiting today.</p>}</div>{msg&&<p className="message status">{msg}</p>}</section></div>
}
