import React,{useEffect,useState}from'react'

export default function FamilyOperations({household,supabase}){
 const[kind,setKind]=useState('grocery'),[items,setItems]=useState([]),[title,setTitle]=useState(''),[privateItem,setPrivateItem]=useState(false),[userId,setUserId]=useState(''),[msg,setMsg]=useState('')
 async function load(){const{data:{user}}=await supabase.auth.getUser();setUserId(user.id);const{data,error}=await supabase.from('ft_household_items').select('*').eq('household_id',household.id).eq('kind',kind).eq('completed',false).order('created_at');setItems(data||[]);if(error)setMsg(error.message)}
 useEffect(()=>{load()},[household.id,kind])
 async function add(e){e.preventDefault();const{error}=await supabase.from('ft_household_items').insert({household_id:household.id,created_by:userId,kind,title:title.trim(),private:kind==='prayer'&&privateItem});setMsg(error?error.message:`${kind==='grocery'?'Grocery item':kind==='prayer'?'Prayer':'Meeting topic'} added.`);if(!error){setTitle('');load()}}
 async function complete(item){const{error}=await supabase.from('ft_household_items').update({completed:true,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',item.id);setMsg(error?error.message:'Completed.');if(!error)load()}
 const names={grocery:'Grocery list',prayer:'Prayer list',meeting:'Family meeting'}
 return <div className="page familyoperations"><section className="panel"><p className="kicker">FAMILY OPERATING SYSTEM</p><h2>Shared life without scattered lists.</h2><nav className="operationtabs">{Object.entries(names).map(([id,name])=><button className={kind===id?'active':''} onClick={()=>setKind(id)} key={id}>{name}</button>)}</nav><form onSubmit={add}><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==='grocery'?'Add something to buy…':kind==='prayer'?'Add a prayer request…':'Add an agenda topic…'}/>{kind==='prayer'&&<label className="privateitem"><input type="checkbox" checked={privateItem} onChange={e=>setPrivateItem(e.target.checked)}/> Private to me</label>}<button className="primary">Add</button></form><div className="operationlist">{items.map(item=><article key={item.id}><button onClick={()=>complete(item)} aria-label={`Complete ${item.title}`}>✓</button><div><strong>{item.title}</strong><small>{item.private?'Private':'Shared with family'}</small></div></article>)}{!items.length&&<p className="muted">Nothing waiting here.</p>}</div>{msg&&<p className="message status">{msg}</p>}</section></div>
}
