import React,{useEffect,useState}from'react'

export default function LifeAssistant({household,supabase,localDateKey}){
 const[state,setState]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setMsg('');const{data:{user}}=await supabase.auth.getUser(),today=localDateKey();const[{data:settings},{data:tasks},{data:water},{data:food},{data:checks},{data:plan},{data:{session}}]=await Promise.all([supabase.from('ft_member_settings').select('*').eq('household_id',household.id).eq('user_id',user.id).single(),supabase.from('ft_tasks').select('*').eq('assigned_to',user.id).eq('status','open').or(`due_date.is.null,due_date.lte.${today}`).order('priority',{ascending:false}).order('due_time'),supabase.from('ft_water_logs').select('ounces').eq('user_id',user.id).eq('logged_on',today),supabase.from('ft_food_logs').select('calories,protein_g').eq('user_id',user.id).eq('logged_on',today),supabase.from('ft_daily_checkins').select('*').eq('user_id',user.id).order('program_cycle',{ascending:false}).order('program_day',{ascending:false}).limit(8),supabase.from('ft_daily_plans').select('*').eq('household_id',household.id).eq('user_id',user.id).eq('planned_on',today).maybeSingle(),supabase.auth.getSession()]);let events=[],weather=null,home=[];try{const result=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ft-google-calendar`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'events'})}).then(r=>r.json());events=(result.events||[]).filter(e=>(e.start?.includes('T')?localDateKey(e.start):e.start)===today).slice(0,4)}catch{}try{const result=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ft-home-assistant`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'states'})}).then(r=>r.json());home=(result.entities||[]).filter(e=>['lock','climate'].includes(e.domain)).slice(0,4)}catch{}try{const result=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ft-home-assistant`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'weather'})}).then(r=>r.json());weather=result.weather||null}catch{}setState({user,settings:settings||{},tasks:tasks||[],water:(water||[]).reduce((a,x)=>a+Number(x.ounces),0),calories:(food||[]).reduce((a,x)=>a+Number(x.calories),0),protein:(food||[]).reduce((a,x)=>a+Number(x.protein_g),0),check:checks?.[0],recent:checks||[],events,weather,home,plan:plan||null})}
 useEffect(()=>{load()},[household.id])
 if(!state)return null
 const done=state.check?.completed_actions?.length||0,goal=state.settings.hydration_goal_oz||64,hour=new Date().getHours(),suggested=done<5?`Complete faithful step ${done+1}`:state.tasks[0]?.title||'Protect the rhythm you built',priority=state.plan?.focus||suggested,streak=state.recent.filter(x=>['complete','modified'].includes(x.status)).length
 const homeSummary=state.home.length?`${state.home[0].display_name}: ${state.home[0].state}${state.home.length>1?` · +${state.home.length-1} more`:''}`:'No priority home devices'
 async function savePlan(changes,message){setBusy(true);const row={household_id:household.id,user_id:state.user.id,planned_on:localDateKey(),focus:state.plan?.focus||suggested,simplified:state.plan?.simplified||false,updated_at:new Date().toISOString(),...changes};const{error}=await supabase.from('ft_daily_plans').upsert(row,{onConflict:'household_id,user_id,planned_on'});setBusy(false);setMsg(error?error.message:message);if(!error)setState({...state,plan:row})}
 async function moveTask(){const task=state.tasks[0];if(!task)return setMsg('There is no open task to move.');const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const{error}=await supabase.from('ft_tasks').update({due_date:localDateKey(tomorrow)}).eq('id',task.id);setMsg(error?error.message:`“${task.title}” moved to tomorrow.`);if(!error)load()}
 return <div className="page lifeassistant"><section className="assistantbrief"><div><p className="kicker">PERSONAL DAILY CONCIERGE</p><h2>{state.plan?.simplified?'Today has been simplified.':'Your next right step is clear.'}</h2><strong>{priority}</strong><p>{hour<12?'Build momentum before the day gets crowded.':hour<17?'Choose what matters most for the rest of today.':'Finish faithfully, then let the day end.'}</p></div><button onClick={load}>Refresh overview</button></section><div className="conciergeactions"><button disabled={busy} onClick={()=>savePlan({focus:suggested},'Your focus is set for today.')}>Make this my focus</button><button className={state.plan?.simplified?'active':''} disabled={busy} onClick={()=>savePlan({simplified:!state.plan?.simplified},state.plan?.simplified?'Full plan restored.':'Today simplified to the essentials.')}>{state.plan?.simplified?'Restore full day':'Simplify today'}</button><button disabled={busy||!state.tasks.length} onClick={moveTask}>Move first task to tomorrow</button></div><div className="assistantgrid"><article><span>Today</span><strong>{state.events.length} events · {state.tasks.length} tasks</strong><small>{state.events[0]?.summary||state.tasks[0]?.title||'Your schedule has breathing room.'}</small></article><article><span>Wellness</span><strong>{done}/5 steps · {state.water}/{goal} oz</strong><small>{Math.round(state.calories)} cal · {Math.round(state.protein)}g protein</small></article><article><span>Outside</span><strong>{state.weather?.temperature_f==null?'Weather unavailable':`${state.weather.temperature_f}°F · ${state.weather.description}`}</strong><small>{state.weather?.city||'Local forecast'}</small></article><article><span>Home</span><strong>{homeSummary}</strong><small>Locks and comfort at a glance</small></article></div><div className="assistantcoach"><strong>{streak>=5?'Protect your consistency.':streak>=2?'Momentum is forming.':'Make today the restart.'}</strong><span>{streak} of your latest {state.recent.length||0} recorded days were completed or honestly modified.</span></div>{msg&&<p className="message status">{msg}</p>}</div>
}
