import React, { useState } from 'react'

const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()

export default function NaturalActions({supabase,localDateKey}){
 const[text,setText]=useState(''),[actions,setActions]=useState([]),[msg,setMsg]=useState('')
 async function callHome(action,extra={}){const{data:{session}}=await supabase.auth.getSession();return fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/ft-home-assistant`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}).then(r=>r.json())}
 async function preview(){const proposed=[];let match
  if((match=text.match(/(?:add|log)\s+([\d.]+)\s*(?:oz|ounces?)\s+(?:of\s+)?water/i)))proposed.push({type:'water',amount:Number(match[1]),label:`Add ${match[1]} oz of water`})
  if((match=text.match(/(?:record|set|log)\s+([\d,]+)\s+steps/i)))proposed.push({type:'steps',amount:Number(match[1].replace(/,/g,'')),label:`Set today’s steps to ${match[1]}`})
  if((match=text.match(/(?:record|set|log)\s+(?:my\s+)?weight(?:\s+to)?\s+([\d.]+)/i)))proposed.push({type:'weight',amount:Number(match[1]),label:`Record weight as ${match[1]} lb`})
  if((match=text.match(/(?:add|create)\s+(?:a\s+)?task\s+[“"]?(.+?)[”"]?(?:\s+for\s+(today|tomorrow))?(?:[,.]|$)/i))){const title=match[1].replace(/[”"]$/,'').trim();proposed.push({type:'task',title,when:match[2]||'today',label:`Add task “${title}” for ${match[2]||'today'}`})}
  if((match=text.match(/(?:prayer|note|journal)(?:\s+note)?\s*[:,-]\s*(.+?)(?:\.|$)/i)))proposed.push({type:'note',note:match[1].trim(),label:`Add private note: “${match[1].trim()}”`})
  if((match=text.match(/(?:log|add)\s+(.+?)\s+(?:with|at)\s+([\d,]+)\s+calories?(?:\s+and\s+([\d.]+)\s*g?\s*protein)?/i)))proposed.push({type:'food',title:match[1].trim(),calories:Number(match[2].replace(/,/g,'')),protein:Number(match[3]||0),label:`Log ${match[1].trim()} · ${match[2]} cal${match[3]?` · ${match[3]}g protein`:''}`})
  const deviceMatch=text.match(/\b(lock|unlock)\s+(?:the\s+)?(.+?)(?:[,.]|$)/i)
  if(deviceMatch){const states=await callHome('states').catch(()=>({entities:[]})),command=deviceMatch[1].toLowerCase(),target=normalize(deviceMatch[2]),entity=(states.entities||[]).filter(e=>e.domain==='lock').find(e=>normalize(`${e.display_name} ${e.room}`).includes(target)||target.includes(normalize(e.display_name)));proposed.push(entity?{type:'device',entity,command,label:`${command.replace(/^./,x=>x.toUpperCase())} ${entity.display_name} · ${entity.room||'Other'}`}:{type:'unsupported',label:`Could not safely identify “${deviceMatch[2].trim()}”`})}
  setActions(proposed.length?proposed:[{type:'unsupported',label:'No supported action was recognized. Try the examples below.'}]);setMsg('Review every action. Nothing has changed yet.')
 }
 async function context(){const{data:{user}}=await supabase.auth.getUser();const{data:h}=await supabase.from('ft_households').select('id').limit(1).single();const{data:s}=await supabase.from('ft_member_settings').select('*').eq('household_id',h.id).eq('user_id',user.id).single();const start=s.personal_start_date?new Date(`${s.personal_start_date}T00:00:00`):new Date(),day=Math.max(1,Math.min(75,Math.floor((new Date().setHours(0,0,0,0)-start.setHours(0,0,0,0))/86400000)+1));return{user,h,s,day,cycle:s.program_cycle||1}}
 async function confirm(){if(actions.some(a=>a.type==='unsupported'))return setMsg('Remove or reword the unsupported action before confirming.');setMsg('Applying confirmed actions…');const c=await context();for(const action of actions){let error;if(action.type==='water')({error}=await supabase.from('ft_water_logs').insert({household_id:c.h.id,user_id:c.user.id,logged_on:localDateKey(),ounces:action.amount}));if(action.type==='task'){const due=new Date();if(action.when==='tomorrow')due.setDate(due.getDate()+1);({error}=await supabase.from('ft_tasks').insert({household_id:c.h.id,created_by:c.user.id,assigned_to:c.user.id,title:action.title,due_date:localDateKey(due),visibility:'private'}))}if(action.type==='food')({error}=await supabase.from('ft_food_logs').insert({household_id:c.h.id,user_id:c.user.id,logged_on:localDateKey(),meal:'meal',food_name:action.title,source:'Command box',serving_label:'1 entry',quantity:1,calories:action.calories,protein_g:action.protein,carbs_g:0,fat_g:0}));if(['steps','weight','note'].includes(action.type)){const{data:old}=await supabase.from('ft_daily_checkins').select('*').eq('household_id',c.h.id).eq('user_id',c.user.id).eq('program_cycle',c.cycle).eq('program_day',c.day).maybeSingle();const row={household_id:c.h.id,user_id:c.user.id,program_cycle:c.cycle,program_day:c.day,capacity:old?.capacity||'green',completed_actions:old?.completed_actions||[],status:old?.status||'in_progress',updated_at:new Date().toISOString()};if(action.type==='steps')row.steps=action.amount;if(action.type==='weight')row.weight_lbs=action.amount;if(action.type==='note')row.journal_text=[old?.journal_text,action.note].filter(Boolean).join('\n');({error}=await supabase.from('ft_daily_checkins').upsert(row,{onConflict:'household_id,user_id,program_cycle,program_day'}))}if(action.type==='device'){const extra=action.entity.domain==='lock'?{command:action.command}:{command:action.command};const result=await callHome('control',{entity_id:action.entity.entity_id,...extra});error=result.error?new Error(result.error):null}if(error)return setMsg(error.message||'An action could not be completed. Earlier confirmed actions were saved.')}setMsg('All confirmed actions were completed.');setText('');setActions([]);setTimeout(()=>window.location.reload(),700)}
 return <div className="page naturalactions"><section><p className="kicker">COMMAND FAITHFUL TOGETHER</p><h2>Say what you want done.</h2><p>Supported now: water, steps, weight, private tasks, food totals, prayer notes, and approved locks. Every action requires confirmation.</p><textarea value={text} onChange={e=>{setText(e.target.value);setActions([])}} placeholder={'Add 20 oz of water, record 7,500 steps, and add task “call the dentist” for tomorrow'}/><button className="primary" disabled={!text.trim()} onClick={preview}>Review actions</button>{actions.length>0&&<div className="actionpreview"><strong>Proposed changes</strong>{actions.map((action,index)=><article className={action.type==='unsupported'?'unsupported':''} key={`${action.type}-${index}`}><span>{action.type==='unsupported'?'!':'✓'}</span><p>{action.label}</p></article>)}<small>Only the actions listed above will run. The original sentence itself is not executed.</small><button className="primary" disabled={actions.some(a=>a.type==='unsupported')} onClick={confirm}>Confirm and apply</button></div>}{msg&&<p className="message status">{msg}</p>}<details><summary>Examples</summary><ul><li>Add 16 oz of water</li><li>Record 7,500 steps</li><li>Set my weight to 218.4</li><li>Add task “call the dentist” for tomorrow</li><li>Prayer note: Give me patience today</li><li>Log turkey sandwich with 420 calories and 28g protein</li><li>Lock the front door</li></ul></details></section></div>
}
