import React, { useEffect, useState } from 'react'

export default function ProgressVisuals({household,supabase}){
 const[state,setState]=useState(null)
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();const[{data:s},{data:m}]=await Promise.all([supabase.from('ft_member_settings').select('*').eq('household_id',household.id).eq('user_id',user.id).single(),supabase.from('ft_household_members').select('life_stage').eq('household_id',household.id).eq('user_id',user.id).single()]);const cycle=s?.program_cycle||1;const{data:rows}=await supabase.from('ft_daily_checkins').select('*').eq('household_id',household.id).eq('user_id',user.id).eq('program_cycle',cycle).order('program_day');setState({rows:rows||[],settings:s||{},teen:m?.life_stage==='teen'})})()},[household.id])
 if(!state)return null
 const faithful=row=>['complete','modified'].includes(row.status),rows=state.rows,done=rows.filter(faithful).length,last=rows.at(-1)?.program_day||0
 let current=0;for(let i=rows.length-1;i>=0&&faithful(rows[i]);i--)current++
 let best=0,run=0;for(const row of rows){run=faithful(row)?run+1:0;best=Math.max(best,run)}
 const bestSteps=Math.max(0,...rows.map(r=>Number(r.steps||0))),recent=rows.slice(-14),maxSteps=Math.max(1,...recent.map(r=>Number(r.steps||0))),heat=rows.slice(-28),actions=['Faith','Body','Fuel','Growth','Together']
 const weights=rows.filter(r=>Number(r.weight_lbs)>0),weightChange=weights.length>1?Number(weights.at(-1).weight_lbs)-Number(weights[0].weight_lbs):null
 const milestones=[done>=1&&['First faithful day','You began.'],done>=5&&['Five-day foundation','Consistency has a foothold.'],best>=7&&['Seven-day rhythm','A full week of faithful days.'],last>=38&&['Past halfway','The path is more than half complete.'],last>=75&&['Seventy-five days','You completed the full journey.']].filter(Boolean)
 return <div className="page progressvisuals"><section className="milestonehero"><div><p className="kicker">MOMENTUM</p><h2>{current?`${current}-day faithful streak`:'The next faithful day starts the streak.'}</h2><p>Modified and recovery days count when you complete them honestly.</p></div><div className="journeydial" style={{'--journey':`${last/75*100}%`}}><strong>{last}</strong><span>of 75</span></div></section><div className="personalbestgrid"><article><strong>{best}</strong><span>best faithful streak</span></article><article><strong>{done}</strong><span>faithful days</span></article><article><strong>{bestSteps?bestSteps.toLocaleString():'—'}</strong><span>personal-best steps</span></article>{!state.teen&&<article><strong>{weightChange===null?'—':`${weightChange>0?'+':''}${weightChange.toFixed(1)} lb`}</strong><span>cycle weight direction</span></article>}</div><section className="panel"><h2>Recent step rhythm</h2><div className="stepbars">{recent.map(row=><div key={row.program_day}><span style={{height:`${Math.max(5,Number(row.steps||0)/maxSteps*100)}%`}} title={`${Number(row.steps||0).toLocaleString()} steps`}/><small>D{row.program_day}</small></div>)}</div>{!recent.some(r=>r.steps)&&<p className="muted">Log steps to reveal your movement rhythm.</p>}</section><section className="panel habitpanel"><h2>Faithful-action heatmap</h2><p className="muted">Each row is a program day. Filled squares are actions you completed.</p><div className="heatlabels">{actions.map(x=><span key={x}>{x}</span>)}</div><div className="habitheat">{heat.map(row=><div className="heatrow" key={row.program_day}><small>D{row.program_day}</small>{actions.map((name,index)=><i className={(row.completed_actions||[]).includes(index)?`filled ${row.capacity}`:''} title={`${name}: ${(row.completed_actions||[]).includes(index)?'complete':'not complete'}`} key={name}/>)}</div>)}</div>{!heat.length&&<p>No check-ins recorded yet.</p>}</section><section className="panel"><h2>Milestones</h2><div className="milestonelist">{milestones.map(([title,note])=><article key={title}><span>✓</span><div><strong>{title}</strong><small>{note}</small></div></article>)}{!milestones.length&&<p className="muted">Your first saved faithful day unlocks the first milestone.</p>}</div></section></div>
}
