import React,{useEffect,useState}from'react'

const average=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0
const change=(current,previous,unit='',digits=0)=>previous?`${current-previous>=0?'+':''}${(current-previous).toFixed(digits)}${unit}`:'—'

export default function ProgressIntelligence({household,supabase,localDateKey}){
 const[data,setData]=useState(null)
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser(),end=localDateKey(),startDate=new Date();startDate.setDate(startDate.getDate()-27);const start=localDateKey(startDate);const[{data:settings},{data:checks},{data:food},{data:water}]=await Promise.all([supabase.from('ft_member_settings').select('*').eq('household_id',household.id).eq('user_id',user.id).single(),supabase.from('ft_daily_checkins').select('*').eq('user_id',user.id).gte('updated_at',`${start}T00:00:00`).order('updated_at'),supabase.from('ft_food_logs').select('logged_on,calories,protein_g').eq('user_id',user.id).gte('logged_on',start).lte('logged_on',end),supabase.from('ft_water_logs').select('logged_on,ounces').eq('user_id',user.id).gte('logged_on',start).lte('logged_on',end)]);setData({settings:settings||{},checks:checks||[],food:food||[],water:water||[]})})()},[household.id])
 if(!data)return <div className="page loadingpane">Finding your patterns…</div>
 const dated=data.checks.map(x=>({...x,date:localDateKey(x.updated_at)})),unique=[...new Map(dated.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date)),current=unique.slice(-7),previous=unique.slice(-14,-7),faithful=rows=>rows.filter(x=>['complete','modified'].includes(x.status)).length,avgSteps=rows=>average(rows.map(x=>Number(x.steps)).filter(Boolean)),avgSleep=rows=>average(rows.map(x=>Number(x.sleep_minutes)).filter(Boolean))/60
 const foodDays=Object.values(data.food.reduce((a,x)=>(a[x.logged_on]??={calories:0,protein:0},a[x.logged_on].calories+=Number(x.calories||0),a[x.logged_on].protein+=Number(x.protein_g||0),a),{})),waterDays=Object.values(data.water.reduce((a,x)=>(a[x.logged_on]=(a[x.logged_on]||0)+Number(x.ounces||0),a),{})),weights=unique.filter(x=>Number(x.weight_lbs)>0),recentWeights=weights.slice(-7).map(x=>Number(x.weight_lbs)),priorWeights=weights.slice(-14,-7).map(x=>Number(x.weight_lbs)),capacity=['green','yellow','red'].map(level=>({level,rows:unique.filter(x=>x.capacity===level)})),bestCapacity=[...capacity].sort((a,b)=>faithful(b.rows)/Math.max(1,b.rows.length)-faithful(a.rows)/Math.max(1,a.rows.length))[0]
 const insights=[];if(current.length<3)insights.push('Keep recording honest days. Three or more check-ins will reveal a useful weekly direction.');else{const delta=faithful(current)-faithful(previous);insights.push(delta>0?`Faithful completion improved by ${delta} day${delta===1?'':'s'} over the prior week.`:delta<0?`Completion is down ${Math.abs(delta)} day${delta===-1?'':'s'}. Simplify the plan before adding more.`:'Completion held steady compared with the prior week.');const stepDelta=avgSteps(current)-avgSteps(previous);if(avgSteps(previous))insights.push(stepDelta>=0?`Average steps rose by ${Math.round(stepDelta).toLocaleString()}.`:`Average steps fell by ${Math.abs(Math.round(stepDelta)).toLocaleString()}; protect one dependable walking window.`);if(bestCapacity.rows.length>=2)insights.push(`${bestCapacity.level[0].toUpperCase()+bestCapacity.level.slice(1)} days have been your most dependable capacity pattern.`)}
 const weekly=[0,1,2,3].map(index=>{const rows=unique.slice(-(index+1)*7,index===0?undefined:-index*7);return{label:index===0?'Current':`${index+1} weeks ago`,value:faithful(rows),total:rows.length}}).reverse()
 return <div className="page progressintelligence"><section className="trendhero"><p className="kicker">PROGRESS INTELLIGENCE</p><h1>Follow the direction, not the noise.</h1><p>Your private records are compared week over week. Missing data is left missing—not guessed.</p></section><div className="trendcards"><article><span>Faithful days</span><strong>{faithful(current)}/{current.length||7}</strong><small>{change(faithful(current),faithful(previous),' days')}</small></article><article><span>Average steps</span><strong>{avgSteps(current)?Math.round(avgSteps(current)).toLocaleString():'—'}</strong><small>{change(avgSteps(current),avgSteps(previous),'',0)} vs prior week</small></article><article><span>Average sleep</span><strong>{avgSleep(current)?`${avgSleep(current).toFixed(1)}h`:'—'}</strong><small>{change(avgSleep(current),avgSleep(previous),'h',1)}</small></article><article><span>Weight trend</span><strong>{recentWeights.length?`${average(recentWeights).toFixed(1)} lb`:'—'}</strong><small>{change(average(recentWeights),average(priorWeights),' lb',1)} rolling average</small></article></div><section className="panel"><h2>Four-week consistency</h2><div className="weektrend">{weekly.map(x=><article key={x.label}><div><i style={{height:`${Math.max(5,x.value/7*100)}%`}}/></div><strong>{x.value}/{x.total||7}</strong><span>{x.label}</span></article>)}</div></section><section className="panel"><h2>What your data is saying</h2><ul className="insightlist">{insights.map(x=><li key={x}>{x}</li>)}</ul></section><section className="panel"><h2>Nutrition and hydration signals</h2><div className="signalgrid"><article><strong>{foodDays.length?Math.round(average(foodDays.map(x=>x.calories))):'—'}</strong><span>average calories on logged days</span></article><article><strong>{foodDays.length?`${Math.round(average(foodDays.map(x=>x.protein)))}g`:'—'}</strong><span>average protein on logged days</span></article><article><strong>{waterDays.length?`${Math.round(average(waterDays))} oz`:'—'}</strong><span>average water on logged days</span></article><article><strong>{Math.max(foodDays.length,waterDays.length)}</strong><span>tracked days in the last 28</span></article></div></section></div>
}
