import React, { useState } from 'react'

export default function UniversalQuickAdd({ household, supabase, localDateKey }) {
  const [open,setOpen]=useState(false),[kind,setKind]=useState('water'),[form,setForm]=useState({amount:'',title:'',calories:'',protein:'',note:''}),[msg,setMsg]=useState('')
  async function context(){const{data:{user}}=await supabase.auth.getUser();const{data:s}=await supabase.from('ft_member_settings').select('*').eq('household_id',household.id).eq('user_id',user.id).single();const start=s.personal_start_date?new Date(`${s.personal_start_date}T00:00:00`):new Date(),day=Math.max(1,Math.min(75,Math.floor((new Date().setHours(0,0,0,0)-start.setHours(0,0,0,0))/86400000)+1));return{user,s,day,cycle:s.program_cycle||1}}
  async function save(){setMsg('Saving…');const c=await context();let error
    if(kind==='water')({error}=await supabase.from('ft_water_logs').insert({household_id:household.id,user_id:c.user.id,logged_on:localDateKey(),ounces:Number(form.amount)}))
    if(kind==='task')({error}=await supabase.from('ft_tasks').insert({household_id:household.id,created_by:c.user.id,assigned_to:c.user.id,title:form.title,due_date:localDateKey(),visibility:'private'}))
    if(kind==='food')({error}=await supabase.from('ft_food_logs').insert({household_id:household.id,user_id:c.user.id,logged_on:localDateKey(),meal:'meal',food_name:form.title,source:'Quick add',serving_label:'1 entry',quantity:1,calories:Number(form.calories||0),protein_g:Number(form.protein||0),carbs_g:0,fat_g:0}))
    if(['steps','weight','note'].includes(kind)){const{data:old}=await supabase.from('ft_daily_checkins').select('*').eq('household_id',household.id).eq('user_id',c.user.id).eq('program_cycle',c.cycle).eq('program_day',c.day).maybeSingle();const row={household_id:household.id,user_id:c.user.id,program_cycle:c.cycle,program_day:c.day,capacity:old?.capacity||'green',completed_actions:old?.completed_actions||[],status:old?.status||'in_progress',updated_at:new Date().toISOString()};if(kind==='steps')row.steps=Number(form.amount);if(kind==='weight')row.weight_lbs=Number(form.amount);if(kind==='note')row.journal_text=[old?.journal_text,form.note].filter(Boolean).join('\n');({error}=await supabase.from('ft_daily_checkins').upsert(row,{onConflict:'household_id,user_id,program_cycle,program_day'}))}
    setMsg(error?error.message:'Saved.');if(!error)setTimeout(()=>{setOpen(false);setMsg('');setForm({amount:'',title:'',calories:'',protein:'',note:''});window.location.reload()},450)
  }
  const valid=kind==='water'||kind==='steps'||kind==='weight'?Number(form.amount)>0:kind==='note'?form.note.trim():form.title.trim()
  return <><button className="universaladd" onClick={()=>setOpen(true)} aria-label="Quick add">+</button>{open&&<div className="quickaddbackdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="quickaddsheet"><header><div><p className="kicker">QUICK ADD</p><h2>Capture it without navigating.</h2></div><button onClick={()=>setOpen(false)} aria-label="Close">×</button></header><div className="quickaddkinds">{[['water','Water'],['food','Food'],['steps','Steps'],['weight','Weight'],['task','Task'],['note','Prayer / note']].map(([id,label])=><button className={kind===id?'active':''} onClick={()=>setKind(id)} key={id}>{label}</button>)}</div>{['water','steps','weight'].includes(kind)&&<label>{kind==='water'?'Ounces':kind==='steps'?'Today’s steps':'Weight (lb)'}<input autoFocus type="number" step={kind==='weight'?'.1':'1'} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label>}{kind==='task'&&<label>Task<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="What needs to be done?"/></label>}{kind==='food'&&<div className="quickaddfood"><label>Food or meal<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Calories<input type="number" value={form.calories} onChange={e=>setForm({...form,calories:e.target.value})}/></label><label>Protein (g)<input type="number" value={form.protein} onChange={e=>setForm({...form,protein:e.target.value})}/></label></div>}{kind==='note'&&<label>Prayer or reflection<textarea autoFocus value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>}<button className="primary quickaddsave" disabled={!valid} onClick={save}>Save {kind}</button>{msg&&<p className="message status">{msg}</p>}</section></div>}</>
}
