import React, { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

export default function VoiceCommand(){
 const[listening,setListening]=useState(false),[msg,setMsg]=useState(''),[host,setHost]=useState(null),[position,setPosition]=useState({top:0}),recognitionRef=useRef(null)
 useEffect(()=>{const attach=()=>{const textarea=document.querySelector('.naturalactions textarea'),section=textarea?.closest('section');if(section&&textarea){setHost(section);setPosition({top:textarea.offsetTop+textarea.offsetHeight-42})}};attach();window.addEventListener('resize',attach);return()=>window.removeEventListener('resize',attach)},[])
 function fill(words){const textarea=document.querySelector('.naturalactions textarea');if(!textarea)return;const setter=Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value')?.set;setter?.call(textarea,words);textarea.dispatchEvent(new Event('input',{bubbles:true}));textarea.focus()}
 function toggle(){if(listening&&recognitionRef.current){setMsg('Stopping…');recognitionRef.current.stop();return}const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return setMsg('Voice input is unavailable here. Use your keyboard microphone or type the command.');try{const recognition=new Recognition();recognitionRef.current=recognition;recognition.lang='en-US';recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>{setListening(true);setMsg('Listening… Tap the microphone again to stop.')};recognition.onresult=event=>fill(Array.from(event.results).map(result=>result[0].transcript).join(' '));recognition.onerror=event=>{recognitionRef.current=null;setListening(false);setMsg(event.error==='not-allowed'?'Allow microphone access in browser settings, then try again.':'I could not hear that clearly. Please try again.')};recognition.onend=()=>{recognitionRef.current=null;setListening(false);setMsg(current=>current==='Stopping…'||current.startsWith('Listening…')?'Voice captured. Check the words, then review the actions.':current)};recognition.start()}catch{recognitionRef.current=null;setListening(false);setMsg('Voice input could not start. Try the keyboard microphone instead.')}}
 if(!host)return null
 return createPortal(<><button type="button" style={position} className={`voicecommandinline ${listening?'listening':''}`} onClick={toggle} aria-pressed={listening} aria-label={listening?'Stop listening':'Speak what you have done'} title={listening?'Stop listening':'Speak what you have done'}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 15a4 4 0 0 0 4-4V5a4 4 0 0 0-8 0v6a4 4 0 0 0 4 4Zm-2-10a2 2 0 0 1 4 0v6a2 2 0 1 1-4 0V5Zm9 6a7 7 0 0 1-6 6.92V21h3v2H8v-2h3v-3.08A7 7 0 0 1 5 11h2a5 5 0 0 0 10 0h2Z"/></svg></button>{msg&&<small className="voicecommandmessage">{msg}</small>}</>,host)
}
