import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'},json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}}),domains=['light','switch','scene','fan','climate','camera','lock','sensor'];
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),base=(Deno.env.get('HOME_ASSISTANT_URL')||'').replace(/\/$/,''),token=Deno.env.get('HOME_ASSISTANT_TOKEN')||'',jwt=(req.headers.get('Authorization')||'').replace('Bearer ',''),{data:{user}}=await sb.auth.getUser(jwt);if(!user)return json({error:'Sign in required'},401);const{data:m}=await sb.from('ft_household_members').select('*').eq('user_id',user.id).limit(1).single();if(!m)return json({error:'Household required'},403);const body=await req.json().catch(()=>({})),ha=(path:string,init:RequestInit={})=>fetch(`${base}/api${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})}});if(!base||!token)return json({error:'Home Assistant is not configured'},503);
if(body.action==='available'){if(m.role!=='admin')return json({error:'Admin required'},403);const r=await ha('/states');if(!r.ok)return json({error:'Home Assistant connection failed'},502);const states=await r.json(),visible=states.filter((x:any)=>{const d=x.entity_id.split('.')[0];return domains.includes(d)&&(d!=='sensor'||x.attributes?.device_class==='temperature')}),entities=await Promise.all(visible.map(async(x:any)=>{const tr=await ha('/template',{method:'POST',body:JSON.stringify({template:`{{ area_name('${x.entity_id}') or 'No area assigned' }}`})}),area=tr.ok?(await tr.text()).trim()||'No area assigned':'No area assigned';return{entity_id:x.entity_id,domain:x.entity_id.split('.')[0],name:x.attributes.friendly_name||x.entity_id,state:x.state,area}}));return json({entities})}
if(body.action==='save'){if(m.role!=='admin')return json({error:'Admin required'},403);const list=Array.isArray(body.entities)?body.entities:[],enriched=[];for(const x of list){if(!domains.includes(x.domain))continue;const tr=await ha('/template',{method:'POST',body:JSON.stringify({template:`{{ area_name('${x.entity_id}') or 'Other' }}`})}),room=tr.ok?(await tr.text()).trim()||'Other':'Other';enriched.push({household_id:m.household_id,entity_id:x.entity_id,display_name:x.name,domain:x.domain,room})}await sb.from('ft_home_entities').delete().eq('household_id',m.household_id);if(enriched.length)await sb.from('ft_home_entities').insert(enriched);return json({saved:true})}
if(body.action==='weather'){const configResponse=await ha('/config');if(!configResponse.ok)return json({error:'Home location unavailable'},502);const config=await configResponse.json(),lat=Number(config.latitude),lon=Number(config.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return json({error:'Set the home location in Home Assistant'},400);const headers={Accept:'application/geo+json','User-Agent':'FaithfulTogether/1.0 (faithful.104.236.27.61.nip.io)'},pointResponse=await fetch(`https://api.weather.gov/points/${lat.toFixed(4)},${lon.toFixed(4)}`,{headers});if(!pointResponse.ok)return json({error:'National Weather Service location lookup failed'},502);const point=await pointResponse.json(),stationsResponse=await fetch(point.properties.observationStations,{headers});if(!stationsResponse.ok)return json({error:'National Weather Service station lookup failed'},502);const stations=await stationsResponse.json(),station=stations.features?.[0];if(!station)return json({error:'No nearby National Weather Service station found'},404);const observationResponse=await fetch(`${station.id}/observations/latest`,{headers});if(!observationResponse.ok)return json({error:'Current National Weather Service observation unavailable'},502);const observation=await observationResponse.json(),p=observation.properties,tempC=Number(p.temperature?.value),humidity=Number(p.relativeHumidity?.value);return json({weather:{temperature_f:Number.isFinite(tempC)?Math.round((tempC*9/5+32)*10)/10:null,description:p.textDescription||'Current conditions',humidity:Number.isFinite(humidity)?Math.round(humidity):null,observed_at:p.timestamp||null,station:station.properties?.name||'National Weather Service',city:point.properties?.relativeLocation?.properties?.city||'',state:point.properties?.relativeLocation?.properties?.state||'',source:'National Weather Service'}})}
const{data:allowed}=await sb.from('ft_home_entities').select('*').eq('household_id',m.household_id).eq('enabled',true),entity=allowed?.find((x:any)=>x.entity_id===body.entity_id);
if(body.action==='camera_image'){if(!entity||entity.domain!=='camera')return json({error:'Camera not allowed'},403);const r=await ha(`/camera_proxy/${encodeURIComponent(entity.entity_id)}`,{headers:{Accept:'image/*'}});if(!r.ok)return json({error:'Camera image unavailable'},502);return new Response(await r.arrayBuffer(),{status:200,headers:{...cors,'Content-Type':r.headers.get('Content-Type')||'image/jpeg','Cache-Control':'no-store'}})}
if(body.action==='control'){
 if(!entity)return json({error:'Device not allowed'},403);let domain=entity.domain,service='',payload:any={entity_id:entity.entity_id};
 if(domain==='camera')return json({error:'Use camera refresh to view this device'},400);if(domain==='sensor')return json({error:'Sensors are view only'},400);
 if(domain==='light'&&Number.isFinite(Number(body.brightness_pct))){service='turn_on';payload.brightness_pct=Math.max(1,Math.min(100,Number(body.brightness_pct)))}
 else if(domain==='fan'&&Number.isFinite(Number(body.percentage))){service='set_percentage';payload.percentage=Math.max(0,Math.min(100,Number(body.percentage)))}
 else if(domain==='climate'&&Number.isFinite(Number(body.temperature))){service='set_temperature';payload.temperature=Number(body.temperature)}
 else if(domain==='climate'&&body.hvac_mode){service='set_hvac_mode';payload.hvac_mode=String(body.hvac_mode)}
 else if(domain==='lock'){service=body.command==='unlock'?'unlock':'lock'}
 else if(domain==='scene'){service='turn_on'}
 else{service='toggle'}
 const r=await ha(`/services/${domain}/${service}`,{method:'POST',body:JSON.stringify(payload)});if(!r.ok)return json({error:`${domain} control failed`},502);if(domain==='lock'){for(let attempt=0;attempt<6;attempt++){await new Promise(resolve=>setTimeout(resolve,500));const status=await ha(`/states/${encodeURIComponent(entity.entity_id)}`);if(status.ok){const current=(await status.json()).state;if(current!=='locking'&&current!=='unlocking')break}}}
}
const r=await ha('/states');if(!r.ok)return json({error:'Home Assistant connection failed'},502);const states=await r.json();return json({connected:true,is_admin:m.role==='admin',entities:(allowed||[]).map((e:any)=>{const s=states.find((x:any)=>x.entity_id===e.entity_id),a=s?.attributes||{};return{...e,state:s?.state||'unavailable',brightness:a.brightness==null?null:Math.round(a.brightness/255*100),supports_brightness:!!a.supported_color_modes?.some((x:string)=>x!=='onoff'),percentage:Number(a.percentage||0),percentage_step:Number(a.percentage_step||1),preset_modes:a.preset_modes||[],current_temperature:a.current_temperature??null,target_temperature:a.temperature??null,min_temp:a.min_temp??50,max_temp:a.max_temp??90,target_temp_step:a.target_temp_step??1,hvac_modes:a.hvac_modes||[],hvac_action:a.hvac_action||'',unit:a.temperature_unit||a.unit_of_measurement||'°F',device_class:a.device_class||''}})})});
